Repository T4g1/gd-wildjam18, pull requests merged in 2020-02, with the labels that each got.

#40 [add] Puzzle 1 SFX
  assets/sfx/level1/sfx_correct.ogg
  assets/sfx/level1/sfx_correct.ogg.import
  assets/sfx/level1/sfx_error.ogg
  assets/sfx/level1/sfx_error.ogg.import
  assets/sfx/level1/tv_antenna_1.ogg
  assets/sfx/level1/tv_antenna_1.ogg.import
  assets/sfx/level1/tv_antenna_2.ogg
  assets/sfx/level1/tv_antenna_2.ogg.import
  assets/sfx/level1/tv_antenna_3.ogg
  assets/sfx/level1/tv_antenna_3.ogg.import
  assets/sfx/level1/tv_channelchange_1.ogg
  assets/sfx/level1/tv_channelchange_1.ogg.import
  assets/sfx/level1/tv_channelchange_2.ogg
  assets/sfx/level1/tv_channelchange_2.ogg.import
  assets/sfx/level1/tv_channelchange_3.ogg
  assets/sfx/level1/tv_channelchange_3.ogg.import
  levels/puzzles/TVPuzzle.gd
  levels/puzzles/TVPuzzle.tscn
Labels: audio: SFX, code, priority: low

#38 [add] Credit scene
  assets/player_spriteframes.tres
  sources/Utils.gd
  sources/game/Game.gd
  sources/game/Game.tscn
  sources/menu/Credits.gd
  sources/menu/Credits.tscn
  sources/menu/Splash.gd
Labels: code, priority: low

#36 [add] Level templates
  LevelTornado.gd
  entities/Car.tscn
  entities/GasCan.tscn
  entities/Tires.tscn
  entities/Tools.tscn
  levels/LevelApartment.gd
  levels/LevelApartment.tscn
  levels/LevelShelter.gd
  levels/LevelShelter.tscn
  levels/LevelTornado.tscn
  levels/LevelTsunami.gd
  levels/LevelTsunami.tscn
  levels/LevelWifeHouse.gd
  levels/LevelWifeHouse.tscn
  levels/puzzles/TVPuzzle.gd
  project.godot
  sources/entity/Entity.tscn
  sources/game/Game.gd
  sources/game/Game.tscn
  sources/level/Level.gd
  sources/level/Level.tscn
  sources/player/Player.tscn
  sources/ui/dialog/Dialog.gd
  sources/ui/dialog/Dialog.tscn
  sources/ui/dialog/DialogLine.gd
  sources/ui/dialog/DialogLine.tscn
  sources/ui/dialog/SpeechBubble.gd
  sources/ui/dialog/SpeechBubble.tscn
Labels: code, priority: high

#43 [add] Action level controls
  LevelTornado.gd
  assets/action_tileset.tres
  assets/images/Player-Sheet.png
  assets/images/level3/background.png
  assets/images/level3/background.png.import
  assets/player_spriteframes.tres
  levels/LevelApartment.tscn
  levels/LevelTornado.gd
  levels/LevelTornado.tscn
  levels/LevelWifeHouse.tscn
  project.godot
  sources/FSM.gd
  sources/Spawn.gd
  sources/Spawn.tscn
  sources/State.gd
  sources/game/Game.gd
  sources/obstacle/MovingObstacle.gd
  sources/player/Bouncing.gd
  sources/player/Falling.gd
  sources/player/Idle.gd
  sources/player/Jumping.gd
  sources/player/Player.gd
  sources/player/Player.tscn
  sources/player/Sliding.gd
Labels: code, not ready to merge, priority: high

#46 [add] Assets for level 2
  assets/action_tileset.tres
  assets/images/level2/Sky-layer.png
  assets/images/level2/Sky-layer.png.import
  assets/images/level2/buildings-layer.png
  assets/images/level2/buildings-layer.png.import
  assets/images/level2/city.png
  assets/images/level2/city.png.import
  levels/LevelTornado.tscn
  sources/game/Game.tscn
Labels: graphic, priority: high

#45 [add] Player SFX
  assets/sfx/player/sfx_footstep_1.ogg
  assets/sfx/player/sfx_footstep_1.ogg.import
  assets/sfx/player/sfx_footstep_2.ogg
  assets/sfx/player/sfx_footstep_2.ogg.import
  assets/sfx/player/sfx_footstep_3.ogg
  assets/sfx/player/sfx_footstep_3.ogg.import
  assets/sfx/player/sfx_footstep_4.ogg
  assets/sfx/player/sfx_footstep_4.ogg.import
  assets/sfx/player/sfx_footstep_5.ogg
  assets/sfx/player/sfx_footstep_5.ogg.import
  assets/sfx/player/sfx_footstep_6.ogg
  assets/sfx/player/sfx_footstep_6.ogg.import
  assets/sfx/player/sfx_player_dies.ogg
  assets/sfx/player/sfx_player_dies.ogg.import
  assets/sfx/sfx_dialogtext_1.ogg
  assets/sfx/sfx_dialogtext_1.ogg.import
  assets/sfx/sfx_dialogtext_2.ogg
  assets/sfx/sfx_dialogtext_2.ogg.import
  assets/sfx/sfx_dialogtext_3.ogg
  assets/sfx/sfx_dialogtext_3.ogg.import
  assets/sfx/sfx_dialogtext_4.ogg
  assets/sfx/sfx_dialogtext_4.ogg.import
  assets/sfx/sfx_dialogtext_5.ogg
  assets/sfx/sfx_dialogtext_5.ogg.import
  project.godot
  sources/MultipleAudioStreamPlayer2D.gd
  sources/MultipleAudioStreamPlayer2D.tscn
  sources/level/Level.tscn
  sources/player/Bouncing.gd
  sources/player/Falling.gd
  sources/player/Idle.gd
  sources/player/Jumping.gd
  sources/player/Player.gd
  sources/player/Player.tscn
  sources/ui/dialog/Dialog.gd
  sources/ui/dialog/Dialog.tscn
  sources/ui/dialog/SpeechBubble.gd
  sources/ui/dialog/SpeechBubble.tscn
Labels: audio: SFX, code, priority: high

#44 Update Game.gd to support GUI
  sources/game/Game.gd
  sources/game/Game.tscn
  sources/menu/PauseMenu.gd
  sources/menu/PauseMenu.tscn
Labels: not ready to merge
